"""Pyramid-owned files, atomic replacements, supported-format locks and clock adapters.

No command/facade import. This is the existing per-file publication protocol;
it neither invents a transaction engine nor provides history durability.
"""
from __future__ import annotations
import hashlib
import json
import os
import tempfile
import uuid
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from pyramid_errors import PyramidError
from pyramid_assurance_contracts import PROJECT_FORMAT_VERSION
try:
    import fcntl
except ImportError:  # pragma: no cover - existing Windows fallback
    fcntl = None

UNSUPPORTED_LEGACY_PROJECT = (
    "Unsupported legacy Pyramid project: .pyramid/project.json is missing. "
    "This runtime requires project format V3 and no longer provides V2/V2.1 migration. "
    "Preserve the existing data; if this is a damaged V3 project, restore its original "
    "manifest from backup rather than creating a replacement."
)

def utc_now(*, clock=datetime) -> str:
    return clock.now(timezone.utc).isoformat().replace("+00:00", "Z")


def parse_time(value: str | None, *, clock=datetime) -> datetime | None:
    if not value:
        return None
    try:
        return clock.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


def load_json(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise PyramidError(f"Missing file: {path}") from exc
    except json.JSONDecodeError as exc:
        raise PyramidError(f"Invalid JSON in {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise PyramidError(f"Expected a JSON object in {path}")
    return data


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(data, handle, indent=2, ensure_ascii=False, sort_keys=False)
            handle.write("\n")
        os.replace(temp_name, path)
    except Exception:
        try:
            os.unlink(temp_name)
        except FileNotFoundError:
            pass
        raise


def project_paths(project: str | Path) -> dict[str, Path]:
    root = Path(project).expanduser().resolve()
    meta = root / ".pyramid"
    return {
        "root": root,
        "meta": meta,
        "plan": meta / "plan.json",
        "state": meta / "state.json",
        "project": meta / "project.json",
        "head": meta / "head.json",
        "baseline": meta / "baseline.json",
        "assurance": meta / "assurance.json",
        "graph": meta / "graph.json",
        "ready": meta / "ready.json",
        "events": meta / "events",
        "handoffs": meta / "handoffs",
        "reports": meta / "reports",
        "dossiers": meta / "dossiers",
        "archives": meta / "archives",
        "history": meta / "history",
        "history_index": meta / "history" / "index.json",
        "lock": meta / "lock",
        "docs": root / "docs" / "tasks",
        "html": meta / "pyramid.html",
    }


def require_supported_project(paths: dict[str, Path]) -> None:
    """Reject unsupported current/archive formats before any filesystem mutation."""
    if not paths["plan"].exists():
        return
    if not paths["project"].exists():
        raise PyramidError(UNSUPPORTED_LEGACY_PROJECT)
    manifest = load_json(paths["project"])
    if manifest.get("format_version") != PROJECT_FORMAT_VERSION:
        raise PyramidError(f"Unsupported Pyramid project format; this runtime requires V{PROJECT_FORMAT_VERSION}")


@contextmanager
def project_lock(paths: dict[str, Path]):
    # Existing lock files let us wait for an in-progress V3 reset/restore before
    # checking its manifest. Reject lock-less legacy data without creating files.
    if not paths["lock"].exists():
        require_supported_project(paths)
    paths["meta"].mkdir(parents=True, exist_ok=True)
    with paths["lock"].open("a+", encoding="utf-8") as handle:
        if fcntl is not None:
            fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
        try:
            require_supported_project(paths)
            yield
        finally:
            if fcntl is not None:
                fcntl.flock(handle.fileno(), fcntl.LOCK_UN)


def write_projection_text(path: Path, content: str) -> bool:
    """Skip identical generated bytes, never skip computing current truth."""
    encoded = content.encode('utf-8')
    if path.is_file() and path.read_bytes() == encoded:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f'.{path.name}.', dir=str(path.parent))
    try:
        with os.fdopen(fd, 'wb') as handle:
            handle.write(encoded)
        os.replace(temp_name, path)
    except Exception:
        Path(temp_name).unlink(missing_ok=True)
        raise
    return True


def write_projection_json(path: Path, data: Any, *, writer=write_projection_text) -> bool:
    return writer(path, json.dumps(data, indent=2, ensure_ascii=False) + '\n')


def _event_id(*, clock=datetime) -> str:
    stamp = clock.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    return f"EVENT-{stamp}-{uuid.uuid4().hex[:8].upper()}"


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _handoff_identifier(nid: str, *, clock=datetime) -> str:
    stamp = clock.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    return f"HANDOFF-{nid}-{stamp}-{uuid.uuid4().hex[:8].upper()}"
